language: java

sudo: required


services:
  - docker

install:
  - docker pull mongo


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - mvn -f spring-project/pom.xml verify -Pe2e > /dev/null
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
