language: java

#skip installation step
install:
  - docker pull mongo

services:
  - docker

addons:
  sonarcloud:
    organization: "chiararapicetta-github"
    token:
      secure: "NM2TDLNdHoVreFBPjt/7Nr28PvrFrNctIKxpBYspHRyKKmhyWoVyqmwg9qV3DZPQ3nx5N1YdHNybS+puofH5t58ycU4XvnzwM8pQA1R++x9RBFFLlFMdvN0NNxlJ+IUMJM5urmcvmvP5uChS7CrzAsNWV9HufApurJzdXOVT949zvPSdNqdJlQZc9F5MLI7HB+5n42ZXGFv/XCzvBh/EhEVEB/h9F30oKlJeRc8Pt8hGYMKB1+e5W1Cw0YnzuSpFhpg44A7Nb1CaT0gqeSHmtQ8yUDZBlWNa1FBqmTUV92B/qQKjZrcpHtTPM99eRuMTfJIRssTvBb6rS7WIiKhZD8pNa7aVxeFSfAu5SoV+McCJKxKwFLtqXRCkuvNwPsjE3Xjy0BadYeAHx52X90x3oJNf6ekcQkAMTV+VenkQm6uGyhA6omUjD0YypaO7kJe8C/7r0u0XZrrqx7dmGkpEVLBsayueZ6vPq5WXhJsS9mzl3RuZNK7OI6eDgaApiu723/8pvtnNszzEhej15SbSNlQJqnEyC0ZelMT+cigG/WjUxSOd02GFCQ1h6FqFlVwPhux6JPge+92HBj9eV492ey03CZWbY4vGamp9MuSoTigYP6JHkJXOevIthIYzlg4o1Hoq0oL4lu/PTuT0wxv7w9uewxwCauFiMaDHILDPJjA="


env:
  - DISPLAY=:99.0

before_install:
sh -e /etc/init.d/xvfb start;


script:
  - mvn -f spring-project/pom.xml clean verify -Pjacoco coveralls:report
  - mvn -f spring-project/pom.xml clean verify -Pjacoco sonar:sonar
  - mvn -f spring-project/pom.xml clean verify -Pfailsafe
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
